#!/usr/bin/env python3
"""
landscape_k_coloring.py — Cycle 2 Odd (3-cycle loop, 2026-04-09)

Tests whether the "K-trajectory fingerprint" established for 3-SAT in
landscape_k.py generalizes to a DIFFERENT NP-complete problem family:
3-graph-coloring.

landscape_k.py found:
    Easy SAT  (under-constrained, clause ratio 2.0) → K decreases
    Hard SAT  (phase transition,  clause ratio 4.3) → K flat

Claim to test here:
    Easy 3-coloring (sparse, edge density ≈ 1.5·n)   → K decreases
    Hard 3-coloring (phase transition ≈ 2.35·n)      → K flat

If the K-trajectory fingerprint is domain-specific, we should see a
different pattern here. If it is the universal K-opacity signature of
hard NP problems, the same pattern should appear.

K-proxy: gzip-ratio of the remaining-conflict-edges encoding at each
branching point. As nodes are assigned colors, edges between already-
assigned same-color pairs become CONFLICTS (not satisfied), and edges
between unassigned pairs remain UNRESOLVED. We encode only the
unresolved/conflict subgraph and compress it.

Output: results/landscape_k_coloring_data.json
        results/landscape_k_coloring_findings.md (generated by caller)
"""

import random, time, gzip, json, os
from collections import defaultdict


# ── Graph instance generator ────────────────────────────────────────────────

def gen_coloring_instance(n_nodes, edge_density, seed):
    """
    Generate a 3-colorable random graph by partitioning n nodes into 3
    color classes, then adding edges only between different classes.
    `edge_density` is the expected number of edges per node (average
    degree / 2 is what we aim for: total edges ≈ density * n_nodes).

    Returns (edges, embedded_coloring).
    """
    rng = random.Random(seed * 9973 + n_nodes)
    colors = [rng.randint(0, 2) for _ in range(n_nodes)]

    target_edges = int(edge_density * n_nodes)
    candidate_pairs = [
        (i, j) for i in range(n_nodes) for j in range(i + 1, n_nodes)
        if colors[i] != colors[j]
    ]
    rng.shuffle(candidate_pairs)
    edges = candidate_pairs[:target_edges]
    return edges, colors


# ── K-proxy on unresolved edge subgraph ─────────────────────────────────────

def remaining_edges_to_bytes(edges, coloring_partial, n_nodes):
    """
    Encode the edges that are NOT YET RESOLVED by the partial coloring.
    An edge (u, v) is resolved if both u and v are assigned (satisfied or
    conflict detected). Unresolved edges — those with at least one end
    still free — remain in the search constraint set.

    We encode each unresolved edge as 4 bytes: u_hi, u_lo, v_hi, v_lo.
    """
    unresolved = []
    for u, v in edges:
        u_col = coloring_partial[u]
        v_col = coloring_partial[v]
        if u_col == -1 or v_col == -1:
            unresolved.append((u, v))
    out = bytearray()
    for u, v in unresolved:
        out.append((u >> 8) & 0xFF); out.append(u & 0xFF)
        out.append((v >> 8) & 0xFF); out.append(v & 0xFF)
    return bytes(out)


def k_proxy(data):
    if len(data) == 0:
        return 0.0
    c = gzip.compress(data, compresslevel=9)
    return len(c) / len(data)


# ── Instrumented 3-coloring backtracking ───────────────────────────────────

class ColoringInstrumented:
    """Backtracking 3-coloring with K-proxy instrumentation and a step
    budget. We are not trying to SOLVE hard instances — we are measuring
    the K-trajectory during the first N steps of search. Beyond the
    budget we return `None` with a `budget_exhausted` flag set; the
    recorded k_trajectory up to that point is what we actually want."""

    def __init__(self, n_nodes, edges, k=3, record_every=5, max_steps=20000):
        self.n = n_nodes
        self.edges = edges
        self.k = k
        self.record_every = record_every
        self.max_steps = max_steps
        self.depth_k_values = []
        self.step = 0
        self.decisions = 0
        self.budget_exhausted = False
        self.adj = [set() for _ in range(n_nodes)]
        for u, v in edges:
            self.adj[u].add(v)
            self.adj[v].add(u)

    def solve(self):
        coloring = [-1] * self.n
        return self._backtrack(coloring, 0)

    def _backtrack(self, coloring, node):
        self.step += 1
        if self.step > self.max_steps:
            self.budget_exhausted = True
            return None
        # Record K-proxy at this point.
        if self.step % self.record_every == 0:
            data = remaining_edges_to_bytes(self.edges, coloring, self.n)
            k = k_proxy(data) if len(data) >= 20 else 0.0
            n_assigned = sum(1 for c in coloring if c != -1)
            self.depth_k_values.append({
                "step": self.step,
                "depth": node,
                "n_assigned": n_assigned,
                "k_proxy": round(k, 6),
            })

        if node == self.n:
            return list(coloring)

        neighbor_colors = {coloring[nb] for nb in self.adj[node] if coloring[nb] != -1}
        for c in range(self.k):
            if c not in neighbor_colors:
                coloring[node] = c
                self.decisions += 1
                res = self._backtrack(coloring, node + 1)
                if res is not None:
                    return res
                if self.budget_exhausted:
                    return None
                coloring[node] = -1
        return None


# ── Experiment driver ──────────────────────────────────────────────────────

def run_experiment(n_nodes, edge_density, n_instances=5, seed_base=200,
                   max_steps=20000):
    results = []
    for inst in range(n_instances):
        edges, embedded = gen_coloring_instance(n_nodes, edge_density, seed_base + inst)
        solver = ColoringInstrumented(n_nodes, edges, k=3, record_every=3,
                                      max_steps=max_steps)
        t0 = time.perf_counter()
        sol = solver.solve()
        elapsed = time.perf_counter() - t0
        k_values = [r["k_proxy"] for r in solver.depth_k_values]
        k_initial = k_values[0] if k_values else None
        k_final = k_values[-1] if k_values else None
        k_min = min(k_values) if k_values else None
        if k_values and len(k_values) >= 2:
            k_trend = "decreasing" if k_values[-1] < k_values[0] else "flat/increasing"
        else:
            k_trend = "too_short"
        results.append({
            "instance": inst,
            "n_nodes": n_nodes,
            "edge_density": edge_density,
            "n_edges": len(edges),
            "solved": sol is not None,
            "budget_exhausted": solver.budget_exhausted,
            "decisions": solver.decisions,
            "steps": solver.step,
            "time_ms": round(elapsed * 1000, 4),
            "k_initial": round(k_initial, 4) if k_initial else None,
            "k_final":   round(k_final,   4) if k_final   else None,
            "k_min":     round(k_min,     4) if k_min     else None,
            "k_trend": k_trend,
            "k_trajectory_head": solver.depth_k_values[:20],
        })
    return results


def run():
    print("=" * 70)
    print("3-Coloring Landscape K-Content: Easy vs Hard (Cycle 2 Odd)")
    print("=" * 70)

    configs = [
        # (n_nodes, edge_density, description)
        (20, 1.5, "easy-20 (sparse, density 1.5n)"),
        (20, 2.3, "hard-20 (phase transition ~2.35n)"),
        (30, 1.5, "easy-30 (sparse)"),
        (30, 2.3, "hard-30 (phase transition)"),
    ]

    all_results = []
    for n, density, desc in configs:
        print(f"\n{desc}:")
        batch = run_experiment(n, density, n_instances=3, seed_base=200,
                               max_steps=50000)
        all_results.extend(batch)

        ki = [r["k_initial"] for r in batch if r["k_initial"] is not None]
        kf = [r["k_final"]   for r in batch if r["k_final"]   is not None]
        decs = [r["decisions"] for r in batch]
        down = sum(1 for r in batch if r["k_trend"] == "decreasing")
        solved = sum(1 for r in batch if r["solved"])

        if ki and kf:
            avg_ki = sum(ki) / len(ki)
            avg_kf = sum(kf) / len(kf)
            print(f"  K_initial: {avg_ki:.4f} (avg, {len(ki)} recorded)")
            print(f"  K_final:   {avg_kf:.4f} (avg, {len(kf)} recorded)")
            print(f"  ΔK:        {avg_kf - avg_ki:+.4f}")
        else:
            print(f"  K_initial: N/A (solved before first record)")
        print(f"  Decisions: {sum(decs) / len(decs):.1f} (avg)")
        print(f"  Solved:    {solved}/{len(batch)}")
        print(f"  K decreasing: {down}/{len(batch)}")

    print("\n── Cross-configuration summary ──")
    print(f"{'Config':<38} {'K_init':<10} {'K_final':<10} {'ΔK':<10} {'Decisions':<12} {'K↓'}")
    print("─" * 85)
    for n, density, desc in configs:
        batch = [r for r in all_results if r["n_nodes"] == n and abs(r["edge_density"] - density) < 0.01]
        ki = [r["k_initial"] for r in batch if r["k_initial"] is not None]
        kf = [r["k_final"] for r in batch if r["k_final"] is not None]
        decs = [r["decisions"] for r in batch]
        down = sum(1 for r in batch if r["k_trend"] == "decreasing")
        if ki and kf and decs:
            print(f"{desc:<38} {sum(ki)/len(ki):<10.4f} {sum(kf)/len(kf):<10.4f} "
                  f"{sum(kf)/len(kf) - sum(ki)/len(ki):<10.4f} "
                  f"{sum(decs)/len(decs):<12.1f} {down}/{len(batch)}")
        else:
            print(f"{desc:<38} {'N/A':<10} {'N/A':<10} {'N/A':<10} "
                  f"{sum(decs)/len(decs) if decs else 0:<12.1f} {down}/{len(batch)}")

    print()
    print("Interpretation:")
    print("  Easy density (1.5n): unit-propagation-like pruning → K should decrease")
    print("  Hard density (2.3n): near 3-coloring phase transition → K should be FLAT")
    print()
    print("If the fingerprint matches SAT (decreasing=easy, flat=hard), the")
    print("K-trajectory is a domain-GENERAL signature of search landscape")
    print("opacity, not a 3-SAT artifact. Supports the broader K-manipulation")
    print("framing of P vs NP.")

    os.makedirs("results", exist_ok=True)
    out_path = "results/landscape_k_coloring_data.json"
    with open(out_path, "w") as f:
        json.dump({
            "label": "landscape_k_coloring",
            "date": time.strftime("%Y-%m-%d"),
            "configs": [{"n": c[0], "density": c[1], "desc": c[2]} for c in configs],
            "results": all_results,
        }, f, indent=2)
    print(f"\nManifest → {out_path}")


if __name__ == "__main__":
    run()
